[build]
builder = "DOCKERFILE"

[build.args]
release = "1"

[[plugins]]
id = "postgresql"

[service.variables]
INVIDIOUS_CONFIG = """
database_url: "${{Postgres.DATABASE_URL}}"
hmac_key: "Kobir2026"
check_tables: true
"""
